/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#334529",
        "primary-fixed": "#d3e9c3",
        "primary-fixed-dim": "#b7cda8",
        "primary-container": "#4a5d3f",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#0f2008",
        "on-primary-fixed-variant": "#394c2f",
        "on-primary-container": "#bfd5af",
        "secondary": "#536516",
        "secondary-fixed": "#d5ec8e",
        "secondary-fixed-dim": "#bad075",
        "secondary-container": "#d3e98b",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#161e00",
        "on-secondary-fixed-variant": "#3c4d00",
        "on-secondary-container": "#576a1a",
        "tertiary": "#573745",
        "tertiary-fixed": "#ffd8e6",
        "tertiary-fixed-dim": "#e8bacb",
        "tertiary-container": "#714e5c",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#2d131f",
        "on-tertiary-fixed-variant": "#5e3d4b",
        "on-tertiary-container": "#f0c2d3",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface": "#fbf9f4",
        "surface-dim": "#dbdad5",
        "surface-bright": "#fbf9f4",
        "surface-variant": "#e4e2dd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-container": "#efeee9",
        "surface-container-high": "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "surface-tint": "#516445",
        "background": "#fbf9f4",
        "on-background": "#1b1c19",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#444840",
        "outline": "#74786f",
        "outline-variant": "#c4c8bd",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f1ec",
        "inverse-primary": "#b7cda8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        margin: "32px",
        gutter: "24px",
        max_width: "1280px",
        unit: "8px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "display-lg": ["52px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["36px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-md": ["26px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-lg": ["15px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-sm": ["13px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
